cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from market.views import CategoryListView
from django.contrib.auth import views as auth_views
from social_django import views as social_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', CategoryListView.as_view(), name='category_list'),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls'), name='orders'),
    path('category/', include('market.urls')),
    path('account/', include('django.contrib.auth.urls')),
    path('accounts/', include('users.urls')),
    path('api/v1/', include('api_client.urls')),
    path('coupons/', include(('coupons.urls', 'coupons'), namespace='coupons')),
    path('auth/', include('social_django.urls', namespace='social')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coupons/urls.py
from django.urls import path
from coupons import views


urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int,
        label="Количество",
        widget=forms.Select(attrs={"class": "form-select"})
    )
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

cart/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from market.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from coupons.forms import CouponApplyForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


@login_required
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


@login_required
def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'update': True})
    coupon_apply_form = CouponApplyForm()
    return render(request, 'cart/cart_detail.html',
                  {'cart': cart, 'coupon_apply_form': coupon_apply_form})

templates/cart/cart_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Корзина покупок
{% endblock %}

{% block content %}
    <br>
    <h1>Корзина покупок</h1>
    <table class="table cart">
        <thead>
        <tr>
            <th scope="col">Картинка</th>
            <th scope="col" style="width: 400px">Наименование товар</th>
            <th scope="col" style="width: 120px">Обновить кол-во</th>
            <th scope="col">Удалить</th>
            <th scope="col">Кол-во</th>
            <th scope="col">Цена за шт</th>
            <th scope="col">Общая стоимость</th>
        </tr>
        </thead>
        <tbody style="vertical-align: middle">
        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <img height="80" src="{% if product.get_last_image %}{{ product.get_last_image.url }}{% else %}{% static 'img/1.jpg' %}{% endif %}">
                        </a>
                    </td>
                    <td width="24%"><a href="{% url 'product_detail' slug=product.category.slug pk=product.pk %}">{{ product.product_name }}</a></td>
                    <td>
                        <form action="{% url 'cart:cart_add' product.id %}" method="post">
                            {{ item.update_quantity_form.quantity }}
                            {{ item.update_quantity_form.update }}
                            <input class="btn btn-info" style="margin-top: 10px" type="submit" value="Обновить">
                            {% csrf_token %}
                        </form>
                    </td>
                    <td><a class="btn btn-danger" href="{% url 'cart:cart_remove' product.id %}">Удалить</a></td>
                    <td>
                        {{ item.quantity }} - шт.
                    </td>
                    <td class="num">{{ item.price }} тенге</td>
                    <td class="num"><b>{{ item.total_price }}</b> тенге</td>
                </tr>
            {% endwith %}
        {% endfor %}
        {% if cart.get_total_price %}
            {% if cart.coupon %}
                <tr class="subtotal">
                    <td colspan="5" style="padding: 0; text-align: left; font-size: 18px; background-color: #2aabd2;">
                        <b style="margin-left: 30px">Промежуточный итог</b>
                    </td>
                    <td colspan="2"
                        class="num"
                        style="padding: 0; text-align: right; font-size: 18px; background-color: #2aabd2; ">
                        <span style="margin-right: 30px"><b>{{ cart.get_total_price }}</b> тенге</span>
                    </td>
                </tr>
                <tr>
                    <td colspan="5" style="padding: 0; text-align: left; font-size: 18px; background-color: #5b80b2">
                        <b style="margin-left: 30px">
                            Купон "{{ cart.coupon.code }}"
                            (скидка {{ cart.coupon.discount }}%)
                        </b>
                    </td>
                    <td colspan="2"
                        class="num neg"
                        style="padding: 0; text-align: right; font-size: 18px; background-color: #5b80b2 ">
                        <span style="margin-right: 30px"><b>- {{ cart.get_discount|floatformat:"2" }}</b> тенге</span>
                    </td>
                </tr>
            {% endif %}
            <tr class="total" style="">
                <td colspan="4" style="padding: 0; text-align: left; font-size: 22px; background-color: #2e6da4; color: white">
                    <b style="margin-left: 30px">Всего</b>
                </td>
                <td colspan="3"
                    class="num"
                    style="padding: 0; text-align: right; font-size: 22px; background-color: #2e6da4; color: white">
                    <span style="margin-right: 30px"><b>{{ cart.get_total_price_after_discount|floatformat:"2" }} </b> тенге</span>
                </td>
            </tr>

        {% endif %}
        </tbody>
    </table>

    {% if cart %}
        <form action="{% url "coupons:apply" %}" method="post">
            {% csrf_token %}
            {{ coupon_apply_form }}
            <input type="submit" class="btn btn-secondary" value="Применять">
        </form>
    {% endif %}

    <p style="text-align: right; margin-top: 5%">
        <a href="{% url 'category_list' %}" class="button btn btn-warning">В магазин</a>

        {% if cart.get_total_price %}
            <a href="{% url "order_create" %}" class="button btn btn-success" style="margin-left: 4%">Оформить заказ</a>
        {% endif %}
    </p>
{% endblock %}