cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from market.views import CategoryListView
from django.contrib.auth import views as auth_views
from social_django import views as social_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', CategoryListView.as_view(), name='category_list'),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls'), name='orders'),
    path('category/', include('market.urls')),
    path('account/', include('django.contrib.auth.urls')),
    path('accounts/', include('users.urls')),
    path('api/v1/', include('api_client.urls')),
    path('coupons/', include(('coupons.urls', 'coupons'), namespace='coupons')),
    path('auth/', include('social_django.urls', namespace='social')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <style>
        {% block style %} {% endblock %}
    </style>
</head>
<body>
<div class="container">

    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="\">
                <img src="{% static 'img/logo.svg' %}" alt="Logo" width="50" height="44" class="d-inline-block align-text-top">
                <span>Market</span>
            </a>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0" style="margin: auto">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="\">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'category_create_product_list' %}">Создать продукт</a>
                    </li>
                </ul>

                <div class="account">
                    {% if user.is_authenticated %}
                        <div class="dropdown">
                            <a class="btn btn-outline-dark dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                                User loged in: <b>{{ user.username }}</b>
                            </a>

                            <ul class="dropdown-menu">
                                <li>
                                    <a href="{% url 'user_product_list' %}"><button type="button" class="dropdown-item">Мои созданные продукты</button></a>
                                </li>
                                <li>
                                    <a href="{% url 'password_change' %}"><button type="button" class="dropdown-item">Change pass</button></a>
                                </li>
                                <li>
                                    {% if user.user_profile %}
                                        <a href="{% url 'profile_detail' pk=profiles.pk %}"><button type="button" class="dropdown-item">Detail profile</button></a>
                                    {% endif %}
                                </li>
                                <li>
                                    <a href="{% url 'logout' %}"><button type="button" class="dropdown-item">Log Out</button></a>
                                </li>
                            </ul>
                        </div>

                    {% else %}
                        <p class="username">Not loged in</p>
                        <a href="{% url 'login' %}"><button type="button" class="btn btn-outline-dark">Log In</button></a>
                        <a href="{% url 'register' %}"><button type="button" class="btn btn-outline-dark">Register</button></a>
                    {% endif %}
                </div>

            </div>
        </div>
    </nav>

    <div id="subheader" style="text-align: right; margin-top: 2%" class="position-relative">
        <div class="cart">
            {% with total_items=cart|length %}
                {% if cart|length > 0 %}
                    <a href="{% url 'cart:cart_detail' %}" class="position-absolute top-0 end-0">
                        <span class="btn btn-outline-info">В корзине </span>
                        <img src="{% static 'img/shopping-basket-add256_24909.png' %}" width="100" alt="">
                        <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger"> {{ total_items }}-шт., {{ cart.get_total_price }} тенге
                            <span class="visually-hidden">В корзине</span>
                        </span>
                    </a>

                {% else %}
                    <a href="{% url 'cart:cart_detail' %}" class="position-absolute top-0 end-0 opacity-50">
                        <span class="btn btn-outline-info">Корзина пустая</span>
                        <img src="{% static 'img/shopping-basket-remove256_24901.png' %}" width="100" alt="">

                        <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                            <span class="visually-hidden">Корзина пустая</span>
                        </span>
                    </a>

                {% endif %}
            {% endwith %}
        </div>
    </div>

    {% block content %}{% endblock %}

</div>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js" integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/js-cookie@3.0.5/dist/js.cookie.min.js"></script>

{% block script %} {% endblock %}
</body>
</html>


